[Smoketest] Using exit codes to halt at smoke test if failed

diff --git a/smoketester/src/run_tests b/smoketester/src/run_tests
--- a/smoketester/src/run_tests
+++ b/smoketester/src/run_tests
@@ -41,4 +41,8 @@ fi
 # Hooray
 if [ -z "$HAS_ERROR" ]; then
     printf "\n\nSmoke test Passed\n\n"
+    exit 0
 fi
+
+printf "\n\nSmoke test Failed!\n\n"
+exit 1
