[Documentation] Updating prod install instructions

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,11 +1,14 @@
 #! /bin/bash
 
+if [ ! -f docker-compose.yml ]; then
+    echo "Compose File Not Found!"
+    exit 2
+fi
+
 # Remove all containers and get a basic install up
 
 docker-compose kill     &> /dev/null
 docker-compose rm -f    &> /dev/null
-
-cp "$1" ./docker-compose.yml
 
 docker-compose pull     &> /dev/null
 docker-compose build    &> /dev/null
